# fly.toml app configuration file generated for ihaveaproblemwith on 2023-06-12T18:20:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ihaveaproblemwith"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
